### ISSUE TITLE
phantomjs custom version show a message of error

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/maintainer-quality-tools#161]
Currently we have the following error when a variable is not set:
https://travis-ci.org/Vauxoo/maintainer-quality-tools/jobs/184397727#L2891-L2907

If there is not the variable `PHANTOMJS_VERSION` defined then skip the custom installation

**Comment by hugho-ad** [comment]
@moylop260 can you confirm please

The flake8 erros are these ?
https://travis-ci.org/Vauxoo/maintainer-quality-tools/jobs/184397732#L3070-L3073

and the pr's are 
https://github.com/OCA/maintainer-quality-tools/pull/390
- cherry-pick of 
![image](https://cloud.githubusercontent.com/assets/10233975/21403877/5210c2ec-c784-11e6-8f91-eb3a39f48246.png)

If your answere is yes, then the cherry.pick doesn't work because there is nothing to commit the 3 last commits from you.
![image](https://cloud.githubusercontent.com/assets/10233975/21403754/c3c33768-c783-11e6-88e0-72a54d5cb593.png)


Only was posible get the cherry-pick for last commit in the image ( [commit](4295871b9e0eb2f89be3ed553ab4d5e3ed026181) )
