### ISSUE TITLE
Travis green with errors

### ISSUE THREAD

**Issue by ysantiago** [Vauxoo/maintainer-quality-tools#262]
We have a [PR](https://github.com/Vauxoo/tanner/pull/96) where travis is green but has a test that is throwing an error:

<img width="995" alt="skitch 34" src="https://user-images.githubusercontent.com/11341058/38578402-d969ded6-3cd1-11e8-8b48-d8c1a3a575e3.png">

**Comment by luisg123v** [comment]
@ysantiago 
Tanner was already migrated to GitLab and the project was deleted, so the PR referenced in this issue, along with its Travis log, no longer exist.

Has this occurred again after the migration? If so, could you provide an MR whose pipeline presents this issue?

**Comment by moylop260** [comment]
FYI the first commit of the MR has the issue:
 - https://git.vauxoo.com/vauxoo/tanner/merge_requests/96/commits

**Comment by luisg123v** [comment]
@moylop260 
I came to the conclusion (maybe premature) that this issue can't be replicated. I made [this dummy MR](https://git.vauxoo.com/vauxoo/tanner/merge_requests/133) to revert changes so they are almost equal to [the failing commit](https://git.vauxoo.com/vauxoo/tanner/commit/2b292ff5d1cfe43928f24875039a47de26a8ffb0), excepting `.gitlab-ci.yml` and `oca_dependencies.txt`.

As you can see, in that MR the issue is not present.
